//REGISTER / LOGIN
POST http://localhost:3001/auth/register 
Content-Type: application/json

{
    "username": "Duy Tung 02",
    "password": "1611",
    "fullname": "Nguyen Duy Tung"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "username": "Duy Tung",
    "password" : "1611"
}

//TASK 
###
POST http://localhost:3001/task/add
Content-Type: application/json

{
    "taskname": "Task 02",
    "totalTime" : 200,  
    "deadline" : "Wed, 21 Oct 2015 18:27:50 GMT",
    "importantRate": 5

}

###
PUT http://localhost:3001/task/edit
Content-Type: application/json

{
    "taskId": "618c7b15959b278c13a96a61",
    "taskname": "new task name testing"
}

###
GET http://localhost:3001/task/
Content-Type: application/json

###
DELETE http://localhost:3001/task/delete
Content-Type: application/json

{
    "taskId": "618c7b0c959b278c13a96a5f"
}


//SETTING
###
POST http://localhost:3001/setting/
Content-Type: application/json

{
    "userId" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThjNzUyYWQ5ZGM2YjI0OWYxNzkwZmIiLCJpYXQiOjE2MzY1OTQ5ODZ9.G3AQPKNoGmIf4WdttEczB61yLY6Uw6KbPrDEkYixXi0"
}

###
PUT http://localhost:3001/setting/change
Content-Type: application/json

{
    "pomodoro": 15,
    "breaktime": 10,
    "alarm": "16:00"
}

###
GET http://localhost:3001/setting/

//FRIENDLIST
###
GET http://localhost:3001/friendlist/

###
POST http://localhost:3001/friendlist/add 
Content-Type: application/json

{
    "friendId": "1234"
}
###
DELETE http://localhost:3001/friendlist/delete
Content-Type: application/json

{
    "friendId" : "heheboi"
}

###
POST http://localhost:3001/friendlist/create
Content-Type: application/json






