POST http://localhost:3001/auth/register 
Content-Type: application/json

{
    "username": "Duy Tung",
    "password": "1611",
    "fullname": "Nguyen Duy Tung"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "username": "Duy Tung 02",
    "password" : "1611"
}

###
POST http://localhost:3001/task/add
Content-Type: application/json

{
    "taskname": "Task 01",
    "totalTime" : 100,
    "deadline" : "Wed, 21 Oct 2015 18:27:50 GMT",
    "importantRate": 10

}